// export const APP_NAME = "production"
export const APP_NAME = "production"
export const APP_VERSION = "0.0.1";
export const API_ENDPOINT = "https://sso.dtap.cloud";
export const OAUTH_FREFIX = "/auth/realms/sit-web/protocol/openid-connect/token";
export const CLIENT_ID = "test";
export const CLIENT_SECRET = "34067802-a8fd-4856-b2f8-bf2fd37c9c09";
// export const API_ENDPOINT = "http://10.1.20.142:8180";
// export const OAUTH_FREFIX = "/auth/realms/tinhht/protocol/openid-connect/token";
// export const CLIENT_ID = "tinhht-client-id";
// export const CLIENT_SECRET = "8884ea91-3a03-40c1-954d-2494cf90be20";
